/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadorapp;

import calculadorapp.Funciones;

/**
 *
 * @author paoloescamilla
 */
public class CalculadoraVis extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraVis
     */
    String selection;
    public CalculadoraVis() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtEcuacion = new javax.swing.JTextField();
        btnBasico = new javax.swing.JRadioButton();
        btnSecante = new javax.swing.JRadioButton();
        btnNewton = new javax.swing.JRadioButton();
        btnnewtonconderivada = new javax.swing.JRadioButton();
        btnBiseccion = new javax.swing.JRadioButton();
        launch_btn = new javax.swing.JButton();
        txtderivada = new javax.swing.JTextField();
        txtpuntInicial = new javax.swing.JTextField();
        txtIteraciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtextremoinferior = new javax.swing.JTextField();
        txtextremosuperior = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpuntoinicial = new javax.swing.JTextField();
        txtpuntoinicial2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtEcuacion.setText("x*ln(x)-1");
        txtEcuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcuacionActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBasico);
        btnBasico.setText("Basico");
        btnBasico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBasicoMouseClicked(evt);
            }
        });
        btnBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnSecante);
        btnSecante.setText("Secante");
        btnSecante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecanteMouseClicked(evt);
            }
        });
        btnSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecanteActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNewton);
        btnNewton.setText("Newton");
        btnNewton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewtonMouseClicked(evt);
            }
        });
        btnNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnnewtonconderivada);
        btnnewtonconderivada.setText("Newton Con Derivada");
        btnnewtonconderivada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewtonconderivadaMouseClicked(evt);
            }
        });
        btnnewtonconderivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewtonconderivadaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBiseccion);
        btnBiseccion.setText("Biseccion");
        btnBiseccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBiseccionMouseClicked(evt);
            }
        });
        btnBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiseccionActionPerformed(evt);
            }
        });

        launch_btn.setText("launch");
        launch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launch_btnActionPerformed(evt);
            }
        });

        txtderivada.setText("ln(x)+1");

        txtpuntInicial.setText("1");

        txtIteraciones.setText("100");

        jLabel1.setText("derivada");

        jLabel2.setText("punto inicial");

        jLabel3.setText("iteraciones");

        jLabel4.setText("funcion");

        jLabel5.setText("inferior");

        jLabel6.setText("superior");

        jLabel7.setText("superior");

        jLabel8.setText("punto inicial");

        jLabel9.setText("punto inciial2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(launch_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtpuntoinicial, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtpuntInicial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIteraciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtextremoinferior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtextremosuperior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpuntoinicial2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBiseccion)
                            .addComponent(btnnewtonconderivada)
                            .addComponent(btnNewton)
                            .addComponent(btnSecante)
                            .addComponent(btnBasico))))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtderivada, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtderivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBasico)
                            .addComponent(txtpuntInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBiseccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSecante)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtextremoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtextremosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnNewton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnnewtonconderivada)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpuntoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(launch_btn)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpuntoinicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicoActionPerformed
             selection = "basico"; 
       System.out.println(selection); 

    }//GEN-LAST:event_btnBasicoActionPerformed

    private void launch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launch_btnActionPerformed
 String exp = this.txtEcuacion.getText().trim();
 
 String derivada = this.txtderivada.getText().trim();
 
 String puntoinicial = this.txtpuntInicial.getText().trim();
 
 String iteraciones = this.txtIteraciones.getText().trim();
 
 String extremoinferior = this.txtextremoinferior.getText().trim();
 
 String extremosuperior = this.txtextremosuperior.getText().trim();
 
 String puntoincial = this.txtpuntoinicial.getText().trim();
 
 String puntoinicial2 = this.txtpuntoinicial2.getText().trim();
 
 
 
 
 String resultado;
 
        System.out.println(selection);
        
        switch (selection){
            case "newton":
                System.out.println("entre a newton");
                resultado = Funciones.resolver_exp_newton(exp, derivada, puntoinicial, iteraciones, false);
                System.out.println(resultado);
                break;
                
            case "basico":
                System.out.println("entre a basico");
               resultado = Funciones.resolver_exp(exp);
                System.out.println(resultado);
                break;
                
            case "secante":
                System.out.println("entre a secante");
                resultado = Funciones.resolver_exp_sec(exp,  puntoinicial, puntoinicial2);
                System.out.println(resultado);
                break;
                
            case "newtonconderivada":
                System.out.println("entre a newtonconderivada");
                
                resultado = Funciones.resolver_exp_newton(exp,derivada, puntoinicial, iteraciones, true);
                System.out.println(resultado);
                 break;
                 
            case "biseccion":
                System.out.println("entre a biseccion");
               resultado = Funciones.resolver_exp_bisec(exp, extremoinferior, extremosuperior, iteraciones);
                System.out.println(resultado);
               break;
               
               default:System.out.println("no contamos con eso");
        }
        
    }//GEN-LAST:event_launch_btnActionPerformed

    private void btnNewtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewtonMouseClicked
      selection = "newton"; 
       System.out.println(selection);// TODO add your hselectionandling code here:
    }//GEN-LAST:event_btnNewtonMouseClicked

    private void btnBasicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBasicoMouseClicked
         selection = "basico";
         this.txtpuntInicial.setVisible(false);
          System.out.println(selection);// TODO add your handling code here:
    }//GEN-LAST:event_btnBasicoMouseClicked

    private void btnSecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecanteMouseClicked
        selection = "secante"; 
         System.out.println(selection);// TODO add your handling code here:
    }//GEN-LAST:event_btnSecanteMouseClicked

    private void btnnewtonconderivadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewtonconderivadaMouseClicked
        selection = "newtonconderivada";   
         System.out.println(selection);// TODO add your handling code here:
    }//GEN-LAST:event_btnnewtonconderivadaMouseClicked

    private void btnBiseccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBiseccionMouseClicked
        selection = "biseccion";    
         System.out.println(selection);// TODO add your handling code here:
    }//GEN-LAST:event_btnBiseccionMouseClicked

    
    
    
    
    
    
    private void btnSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecanteActionPerformed
        selection = "secante"; 
       System.out.println(selection); // TODO add your handling code here:
    }//GEN-LAST:event_btnSecanteActionPerformed

    private void btnNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewtonActionPerformed
 selection = "newton"; 
       System.out.println(selection);        
this.txtpuntInicial.setVisible(true);

    }//GEN-LAST:event_btnNewtonActionPerformed

    private void btnnewtonconderivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewtonconderivadaActionPerformed
 selection = "newtonconderivada"; 
       System.out.println(selection);        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewtonconderivadaActionPerformed

    private void btnBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiseccionActionPerformed
 selection = "biseccion"; 
       System.out.println(selection);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBiseccionActionPerformed

    private void txtEcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcuacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraVis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBasico;
    private javax.swing.JRadioButton btnBiseccion;
    private javax.swing.JRadioButton btnNewton;
    private javax.swing.JRadioButton btnSecante;
    private javax.swing.JRadioButton btnnewtonconderivada;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton launch_btn;
    private javax.swing.JTextField txtEcuacion;
    private javax.swing.JTextField txtIteraciones;
    private javax.swing.JTextField txtderivada;
    private javax.swing.JTextField txtextremoinferior;
    private javax.swing.JTextField txtextremosuperior;
    private javax.swing.JTextField txtpuntInicial;
    private javax.swing.JTextField txtpuntoinicial;
    private javax.swing.JTextField txtpuntoinicial2;
    // End of variables declaration//GEN-END:variables
}
